// @ts-ignore -- resolved by the Parcel/Bun build toolchain
import React from 'react';
import { useI18n } from '../i18n';

// ---------------------------------------------------------------------------
// Attribution for lightweight-charts, rendered below the active view ONLY ON
// THE CHART TAB (main.tsx gates this on `activeTab === 'chart'`) - the only
// tab that actually loads/renders that library (it's React.lazy-loaded
// specifically so it's never pulled into the Desk/GEX bundle at all). Its
// Apache-2.0 terms, as stated in the package README, require the
// "attribution notice" from the NOTICE file plus a link to
// https://www.tradingview.com/ "within a display generated by the
// Derivative Works, if and wherever such third-party notices normally
// appear" - scoping this to the one tab that actually generates that display
// is the natural reading, not "every page of the app regardless of whether
// this tab was ever visited". Desk/GEX render `RepoFooter` instead (below).
//
// NOTICE_* below are the two lines of the upstream NOTICE file, VERBATIM
// (github.com/tradingview/lightweight-charts/blob/master/NOTICE, identical at
// tag v5.2.1, the installed version). Legal text: deliberately not routed
// through i18n so it is never translated or reworded. Note the upstream file
// writes the copyright sign as "(" + CYRILLIC SMALL LETTER ES (U+0441) + ")";
// it is kept as-is rather than "corrected".
// ---------------------------------------------------------------------------

export const NOTICE_LINE_1 = 'TradingView Lightweight Charts™';
export const NOTICE_LINE_2 = 'Copyright (с) 2025 TradingView, Inc.';
export const NOTICE_URL = 'https://www.tradingview.com/';

// pb-[3.5px] lg:pb-[11.5px] (NOT a plain pb-4/lg:pb-6 match to the side
// gutter's own px-4/lg:px-6 SCALE - that was tried first and overcorrected):
// the TARGET is the TOTAL bottom whitespace (this footer's own padding-top
// (none) + its text's own line-height/height + padding-bottom) reading the
// same small size as the side gutter (16px / 24px at lg), not a sum of the
// text's own height PLUS a side-gutter-sized padding stacked on top of it.
// Measured live (Playwright, footer padding temporarily zeroed): this
// footer's own single-line text height is ~12.5px regardless of breakpoint
// (text-[10px] leading-tight) - so padding-bottom alone needs to supply only
// the REMAINDER up to the gutter size (16 - 12.5 = 3.5px; 24 - 12.5 = 11.5px
// at lg), not the full 16px/24px gutter value itself stacked after the text.
// A plain pb-4/lg:pb-6 (same px-4/lg:px-6 SCALE as the side gutter) was tried
// first and measured ~37px/~29px total at desktop/narrow widths - roughly
// DOUBLE the 24px/16px side gutter it was meant to match - because it added
// the gutter-sized padding ON TOP of the text's own height instead of
// accounting for it. Known remaining limitation: at very narrow viewports
// (~390px and below) the attribution text itself wraps onto a second line
// (~25px tall) - the total necessarily exceeds the 16px gutter there since
// there's no room to shrink the legally-required notice text further; this
// pb value still minimizes the overshoot rather than adding more on top of
// it, same reasoning as the single-line case.
export const AttributionFooter: React.FC = () => (
    <footer className="mx-auto w-full max-w-3xl px-4 pb-[3.5px] text-center text-[10px] leading-tight text-slate-400 lg:max-w-none lg:px-6 lg:pb-[11.5px]">
        {NOTICE_LINE_1} &middot; {NOTICE_LINE_2}{' '}
        <a href={NOTICE_URL} target="_blank" rel="noopener noreferrer" className="underline decoration-dotted underline-offset-2 hover:text-slate-600 dark:hover:text-slate-200">
            {NOTICE_URL}
        </a>
    </footer>
);

export const REPO_URL = 'https://github.com/daggerok/gex';

/**
 * Footer shown on every tab EXCEPT Chart (which shows `AttributionFooter`
 * instead - see that component's own doc comment for why the two are
 * mutually exclusive, not both-at-once). Same box model (padding/size) as
 * `AttributionFooter` so swapping between the two across tabs doesn't shift
 * the page's bottom whitespace.
 */
export const RepoFooter: React.FC = () => {
    const { t } = useI18n();
    return (
        <footer className="mx-auto w-full max-w-3xl px-4 pb-[3.5px] text-center text-[10px] leading-tight text-slate-400 lg:max-w-none lg:px-6 lg:pb-[11.5px]">
            <a href={REPO_URL} target="_blank" rel="noopener noreferrer" className="underline decoration-dotted underline-offset-2 hover:text-slate-600 dark:hover:text-slate-200">
                {t('footer.github')}
            </a>
        </footer>
    );
};
